language: python # Need python environment for pip

sudo: false # Use container-based infrastructure

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"


before_install:
  - pip install hererocks
  - hererocks lua_install --luarocks ^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  - luarocks install luacov
  - luarocks install luacov-coveralls

install:
  # needed just for tests
  - luarocks install lunitx
  - luarocks install cjson
  - luarocks install wsapi
  - luarocks install orbit

script:
  - cd unittest && lua -lluacov run.lua;

after_success:
  - luacov-coveralls -v -r .. -e ../lua_install
